#!/usr/bin/env tsx
/**
 * One-shot script to invalidate every existing setup token and invite code,
 * regenerating them with the CSPRNG-backed generator from
 * `lib/schools-store.ts`. Run once on production after deploying the W1.3
 * commit.
 *
 *   $ SUPABASE_URL=https://xxx.supabase.co \
 *     SUPABASE_SERVICE_ROLE_KEY=eyJ... \
 *     npm run rotate-tokens:prod
 *
 * Why: codes generated before W1.3 used Math.random (xorshift128+) which
 * is reverse-engineerable from a small number of observed outputs. Any
 * code that was leaked to a single attacker permits prediction of every
 * other code generated by the same Node process. Treat all pre-W1.3
 * codes as compromised. See finding C-7 in
 * docs/security/ClubIt-Security-Assessment.md.
 *
 * What it does:
 *  1. For every school, regenerate student_invite_code, admin_invite_code,
 *     advisor_invite_code with `generateInviteCode`.
 *  2. Set setup_token to NULL (forces re-generation by superadmin via
 *     /api/superadmin/schools/[id]/setup-link).
 *  3. Set *_code_expires_at = now() + 14 days for the new codes.
 *  4. Logs a summary table to stdout. Does NOT print the codes — admins
 *     must fetch new codes through the existing /admin (school admin)
 *     and /superadmin (platform admin) UIs.
 *
 * Idempotent: safe to re-run; each invocation simply rotates everything
 * again.
 */
import { createClient } from '@supabase/supabase-js'
import { generateInviteCode } from '../lib/schools-store'

const URL = process.env.SUPABASE_URL ?? process.env.NEXT_PUBLIC_SUPABASE_URL
const SERVICE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!URL || !SERVICE_KEY) {
  console.error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.')
  process.exit(2)
}

const db = createClient(URL, SERVICE_KEY, { auth: { persistSession: false } })

async function main() {
  console.log(`[rotate] connecting to ${URL.replace(/^https?:\/\//, '').slice(0, 24)}...`)

  const { data: schools, error } = await db
    .from('schools')
    .select('id, name, status')

  if (error) {
    console.error('[rotate] failed to list schools:', error.message)
    process.exit(1)
  }

  if (!schools || schools.length === 0) {
    console.log('[rotate] no schools found. Done.')
    return
  }

  console.log(`[rotate] rotating codes for ${schools.length} school(s)...`)

  const expiry = new Date()
  expiry.setDate(expiry.getDate() + 14)
  const expiresAt = expiry.toISOString()

  let ok = 0
  let failed = 0

  for (const s of schools) {
    const update = {
      student_invite_code: generateInviteCode('STU'),
      admin_invite_code:   generateInviteCode('ADM'),
      advisor_invite_code: generateInviteCode('ADV'),
      student_code_expires_at: expiresAt,
      admin_code_expires_at:   expiresAt,
      advisor_code_expires_at: expiresAt,
      setup_token: null,
      setup_token_expires_at: null,
      setup_completed_at: null,
    }

    const { error: updErr } = await db
      .from('schools')
      .update(update)
      .eq('id', s.id)

    if (updErr) {
      console.error(`  [fail] ${s.id}  ${s.name}: ${updErr.message}`)
      failed++
    } else {
      console.log(`  [ ok ] ${s.id}  ${s.name}  (status=${s.status})`)
      ok++
    }
  }

  console.log(`\n[rotate] done. ok=${ok}  failed=${failed}  total=${schools.length}`)
  console.log('[rotate] next steps:')
  console.log('  1. Tell every school admin their codes have rotated; have them')
  console.log('     re-share via the /admin invite-codes panel.')
  console.log('  2. Generate fresh setup tokens via the superadmin panel for any')
  console.log('     school still in onboarding.')

  process.exit(failed > 0 ? 1 : 0)
}

main().catch((err) => {
  console.error('[rotate] unexpected error:', err)
  process.exit(1)
})
